apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec-c2
  labels:
    app: redis-enterprise
spec:
  # Add fields here
  nodes: 3
  # need to expose api port on LB to make it reachable from other cluster
  services:
    apiService: 
      type: LoadBalancer
  uiServiceType: LoadBalancer
  # the below for A/A routing
  ingressOrRouteSpec:
    apiFqdnUrl: api-rec-c2-redis.lab.local
    dbFqdnSuffix: -db-rec-c2-redis.lab.local
    ingressAnnotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      kubernetes.io/ingress.class: nginx
    method: ingress