apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec2
  labels:
    app: redis-enterprise
spec:
  # Add fields here
  nodes: 3
  # undocumenting the below will enable LB access to API/UI if no Ingress is available.
  #services:
  #  apiService: 
  #    type: LoadBalancer
  #uiServiceType: LoadBalancer
  # the below for A/A routing
  ingressOrRouteSpec:
    apiFqdnUrl: api-rec2-redis.lab
    dbFqdnSuffix: -db-rec2-redis.lab
    ingressAnnotations:
 #     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
       # we need to add this annotation or the operator will choke - will be patched with the correct value later.
      kubernetes.io/ingress.class: nginx
    method: ingress