apiVersion: v1
kind: Pod
metadata:
  name: rediscli
  namespace: redis
spec:
  containers:
  - name: redis
    image: REDIS_IMAGE
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always