apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-benchmark-deployment
  namespace: redis
  labels:
    app: redis-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-benchmark
  template:
    metadata:
      labels:
        app: redis-benchmark
    spec:
      containers:
        - name: redis-benchmark-go
          image: ruurdk/redis-benchmark-go:latest
          args:
            - -tls
            - -tls-skip
            - -d
            - '100'
            - -c
            - '25'
            - -h
            - db1-headless.redis.svc
            - -p
            - '13762'
            - -rps
            - '5000'
            - -l
            - SET
            - __key__
            - __data__
