apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ippool1
  namespace: metallb-system
spec:
  addresses:  
  - 172.18.253.2-172.18.253.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
---