apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ippool
  namespace: metallb-system
spec:
  addresses:
  - 10.200.0.110-100.200.0.199
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty 
  namespace: metallb-system