apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  #name: <generated>
  labels:
    app: redis-enterprise
spec:
  # Add fields here
  nodes: 3  
  # A/A routing - will be removed when A/A is not enabled
  ingressOrRouteSpec:
    #apiFqdnUrl: <generated>
    #dbFqdnSuffix: <generated>
    ingressAnnotations:
      # we need to add this annotation or the operator will choke - will be patched with the correct value later.
      kubernetes.io/ingress.class: nginx
    method: ingress